# Generated by Django 5.2.4 on 2025-07-28 10:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChaiVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='chais/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('BT', 'Black Tea'), ('CT', 'Classic Tea'), ('GT', 'Green Tea'), ('ET', 'Elaichi Tea'), ('LT', 'Lemon Tea'), ('MT', 'Masala Tea')], max_length=2)),
            ],
        ),
    ]
